---
title: "EDA"
format: pdf
---

```{r include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(forcats)
```


```{r}
#Distribution of winning
whole %>% 
  ggplot()+
  geom_bar(aes(x=won),
           fill="black")+
  ggtitle("Distribitions of Won")+
  xlab("Won")+
  ylab("Count")+
  theme_few()
```
```{r warning=FALSE, message=FALSE}
#Distribution of Horse weight and jockey weight
ph <- whole %>% 
  ggplot()+
  geom_histogram(aes(x=declared_weight))+
  theme_few()+
  ggtitle("Declared Weight of Horse and Jockey in lbs")+
  xlab("")

pj <- whole %>% 
  ggplot()+
  geom_histogram(aes(x=actual_weight))+
  theme_few()+
  ggtitle("Actual Weight Carried by Horse in lbs")+
  xlab("")

grid.arrange(ph,pj)
```
```{r}
whole %>% 
  ggplot()+
  geom_bar(aes(x=distance))+
  theme_few()+
  ggtitle("Distribution of Race Distance")+
  xlab("distance in meters")
```
```{r}
summary(whole$horse_rating)
quantile(whole$horse_rating, probs = c(.1, .2, .8, .9))
```
```{r warning=FALSE, message=FALSE}
whole %>% 
  ggplot()+
  geom_histogram(aes(x=win_odds))+
  theme_few()+
  ggtitle("Distribution of Win Odds")
```
```{r}
whole %>% 
  ggplot()+
  geom_boxplot(aes(x=win_odds,
                   y=won))+
  theme_few()+
  ggtitle("Distribution of Win Odds per Winning")
```

```{r}
whole %>% 
  ggplot() +
  geom_bar(aes(x = fct_infreq(horse_country))) +
  theme_few() +
  xlab("Horse Country") + 
  ylab("Count")+
  ggtitle("Distribution of Horses by Country")
```

```{r}
whole %>% 
  ggplot()+
  geom_bar(aes(x=draw))+
  facet_wrap(~won)
```
```{r}
whole %>% 
  ggplot()+
  geom_bar(aes(x=won))+
  facet_wrap(~draw)
```

```{r warning=FALSE, message=FALSE}
races %>% 
  ggplot()+
  geom_histogram(aes(x=win_dividend1))+
  theme_few()
```

