---
title: "Logistic Regression: Horse Racing"
author: "Kyubin Im, Matthew Murnane, and Ethan Newcomb"
format: revealjs
---

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(readr)
library(ggthemes)
library(forcats)
library(knitr)
library(kableExtra)
```

```{r}

runs <- read_csv("../data/runs.csv")
races <- read_csv("../data/races.csv")

# Join --------------------------------------------------------------------

whole <- inner_join(runs, races, by="race_id")

# Changing Data Classes ---------------------------------------------------

whole$race_id <- as.character(whole$race_id)
whole$horse_no <- as.character(whole$horse_no)
whole$horse_id <- as.character(whole$horse_id)
whole$won <- as.logical(whole$won)
whole$horse_ratings <- as.character(whole$horse_ratings)
whole$draw <- as.character(whole$draw)
whole$jockey_id <- as.character(whole$jockey_id)
whole$trainer_id <- as.character(whole$trainer_id)
whole$race_no <- as.character(whole$race_no)
whole$surface <- as.character(whole$surface)
whole$race_class <- as.character(whole$race_class)
whole$time7 <- as.numeric(whole$time7)
whole$sec_time7 <- as.numeric(whole$sec_time7)
whole$distance <- as.character(whole$distance)
whole$result <- as.character(whole$result)

position_cols <- paste0("position_sec", 1:6)
place_cols <- paste0("place_combination", 1:4)
wincomb_cols <- paste0("win_combination",1:2)

for (col in c(place_cols, position_cols)) {
  whole[[col]] <- as.character(whole[[col]])
}
```

## The Data

- A horse per race is the observation
- 79,447 rows and 73 columns

```{r}
kable(head(whole)) %>%
  kable_styling(font_size = 15, full_width = FALSE)
```

## Pre-Race Variables

```{r}
pre_race_vars <- matrix(c(
  "race_id", "horse_no", "horse_id", "horse_age", "horse_country", "horse_type",
  "horse_rating", "horse_gear", "declared_weight", "actual_weight", "draw", "trainer_id",
  "jockey_id", "win_odds", "place_odds", "distance", "surface", "going",
  "config", "venue", "race_no", "date", "race_class", "prize"
), ncol = 3, byrow = TRUE)

kable(pre_race_vars, col.names = NULL, align = "l") %>%
  kable_styling(full_width = TRUE, position = "center")
```

## Levels of Categorical Variables

```{r}
cat_pre_race_vars <- c( "race_id", "horse_no", "horse_id", "horse_country", "horse_type", "horse_rating", "horse_gear", "draw", "trainer_id", "jockey_id", "distance", "surface", "going", "config", "venue", "race_no", "race_class")

cat_pre_race_vars <- cat_pre_race_vars[cat_pre_race_vars %in% colnames(whole)]

# Get number of unique levels for each
cat_levels <- data.frame(
  Levels = sapply(whole[, cat_pre_race_vars], function(x) length(unique(x)))
)

cat_levels %>%
  arrange(desc(Levels)) %>%
  kable(format = "html", col.names = c("Categorical Variable", "Number of Levels")) %>%
  kable_styling(full_width = FALSE) %>%
  scroll_box(height = "600px")
```

## Rare Event Worry

```{r}
whole %>% 
  ggplot()+
  geom_bar(aes(x=won),
           fill="black")+
  ggtitle("Distribitions of Won")+
  xlab("Won")+
  ylab("Count")+
  theme_few()
```

One in Ten Rule: one predictive variable can be studied for every ten events.

Our proportion of wins is `r round(sum(whole$won)/nrow(whole), 2)`




